// CharacterSelector.cs — Handles swapping between multiple 3D character models.

using UnityEngine;

namespace EndlessRunner.Player
{
    /// <summary>
    /// Stores references to all character models under the Player prefab.
    /// Enables switching them at runtime via the main menu.
    /// </summary>
    public class CharacterSelector : MonoBehaviour
    {
        [Header("Generated by SetupCharacterEditor")]
        public GameObject[] models;
        public Avatar[] avatars;

        private int currentIndex = 0;
        private Animator animator;

        private void Awake()
        {
            animator = GetComponent<Animator>();
        }

        private void Start()
        {
            ApplyCharacter(currentIndex);
        }

        public void CycleCharacter()
        {
            if (models == null || models.Length == 0) return;

            currentIndex++;
            if (currentIndex >= models.Length)
            {
                currentIndex = 0;
            }

            ApplyCharacter(currentIndex);
        }

        private void ApplyCharacter(int index)
        {
            if (models == null || models.Length == 0) return;
            if (index < 0 || index >= models.Length) return;

            // Hide all models
            for (int i = 0; i < models.Length; i++)
            {
                if (models[i] != null)
                {
                    models[i].SetActive(i == index);
                }
            }

            // Update Animator Avatar
            if (animator != null && avatars != null && index < avatars.Length)
            {
                animator.avatar = avatars[index];
            }
        }

        public string GetCurrentCharacterName()
        {
            if (models == null || models.Length == 0) return "NONE";
            if (currentIndex < 0 || currentIndex >= models.Length) return "NONE";

            return models[currentIndex].name.ToUpper();
        }
    }
}
